### PR TITLE
fix: asciinema player with https://cj.rs/gohugo-asciinema/

### PR DESCRIPTION
**Pull request by cljoly**
This uses the `3beta` version of the asciinema module and fixes a couple
paths for some casts.

### CODE REVIEW

**Comment by cljoly** [comment]
image
This works well for me on http://localhost:1313/post/2020_ctcw_2_git/#21-setup

**Comment by cljoly** [comment]
This should fix the issue described in https://github.com/cljoly/gohugo-asciinema/issues/2, although only for the beta branch of the module (master branch of https://github.com/cljoly/gohugo-asciinema is still broken for some reason)

**Comment by PierreMarchand20** [comment]
Thank you for your help!

**Comment by cljoly** [comment]
No worries!

**Pull request merged**
